-Добавлены Entities в соответствии с документом разработки
Transport-company/shop pull request #1
Opened 2021-01-31 16:28 UTC by BrynzaA

-Добавлен API для запроса информации о посылке

2021-01-31 20:07 UTC, ramilmm requested changes

2021-01-31 20:07 UTC, ramilmm commented on src/main/java/com/training/shop/Urls.java
> +        String PART = "info";
Предполагается урл /api/v1/info/5?
Если да, то не очень очевидно info в урле. Может заменить на /api/v1/parcel/5? Или вообще /api/v1/order/5? потому что это же типо заказ с интернет-магазина

2021-01-31 20:07 UTC, ramilmm commented on src/main/java/com/training/shop/controller/ParcelInfoController.java
> +    ResponseEntity<ParcelInfoResponse> getParcelInfo(@PathVariable("id") Long id);
Добавь сразу описание сваггера

2021-01-31 20:07 UTC, ramilmm commented on src/main/java/com/training/shop/controller/client/ParcelInfoClient.java
> +url = "${coreTrackingAPIUrl}")
лучше сделать название параметра более читаемым: core.trackingAPI.url

в application.yaml:

core:
  trackingAPI:
     url: someUrl...

2021-01-31 20:07 UTC, ramilmm commented on src/main/java/com/training/shop/model/Cargo.java
> +    @Column(name = "client")
javadocs над всеми полями моделей, риквестов и респонсов

2021-02-10 12:49 UTC, ramilmm requested changes
Ничего не понял

2021-02-10 12:49 UTC, ramilmm commented on src/main/java/com/training/shop/model/Cargo.java
> +
Пустая строка

2021-02-10 12:49 UTC, ramilmm commented on src/main/java/com/training/shop/model/Shop.java
> +
пустая строка

2021-02-10 12:49 UTC, ramilmm commented on src/main/java/com/training/shop/model/Shop.java
> +import javax.persistence.*;
настрой в идее импорты. Он у тебя схлопывает все импорты в один со звёдочкой. В настройках идеи в поиске imports, там можно задать лимит на схлопывание импортов

2021-02-10 12:49 UTC, ramilmm commented on src/main/java/com/training/shop/service/CartLineInfo.java
> +public interface CartLineInfo {
Это сервис или модель? Что значит CartLineInfo? Похоже на название модели. Название сервиса содержит название модели, с которой он работает, и Service

2021-02-10 12:49 UTC, ramilmm commented on src/main/java/com/training/shop/service/Impl/CartInfoImpl.java
> +public class CartInfoImpl implements CartInfo {
Что с названием сервиса? и где @Service?

2021-02-10 12:49 UTC, ramilmm commented on src/main/java/com/training/shop/service/Impl/CartInfoImpl.java
> +    public CartInfoImpl() {
Если используешь ломбок, то убери пустой конструктор у сервиса. @NoArgsConstructor

2021-02-10 12:49 UTC, ramilmm commented on src/main/java/com/training/shop/service/Impl/CartInfoImpl.java
> +@Data
Зачем эта аннотация сервису?

2021-02-10 12:49 UTC, ramilmm commented on src/main/java/com/training/shop/service/Impl/CartInfoImpl.java
> +        } else {
не понимаю что происходит в этом методе. Это что?

2021-02-10 12:49 UTC, ramilmm commented on src/main/java/com/training/shop/service/Impl/CartInfoImpl.java
> +        CartLineInfoImpl line = this.findLineByName(itemInfo.getName());
а если придёт пустой itemInfo или quantity? Что произойдёт?

2021-02-10 12:49 UTC, ramilmm commented on src/main/java/com/training/shop/service/Impl/CartInfoImpl.java
> +        for (CartLineInfoImpl line: this.cartLines){
а если придёт пустой name? Что произойдёт?

2021-02-10 12:49 UTC, ramilmm commented on src/main/java/com/training/shop/service/Impl/CartInfoImpl.java
> +        CartLineInfoImpl line = this.findLineByName(name);
а если придёт пустой name и quantity? Что произойдёт?

2021-02-10 12:49 UTC, ramilmm commented on src/main/java/com/training/shop/service/Impl/CartInfoImpl.java
> +            if (line.getItemInfo().getName().equals(name)){
а если имя пустое?

2021-02-10 12:49 UTC, ramilmm commented on src/main/java/com/training/shop/service/Impl/CartInfoImpl.java
> +        return null;
зачем возвращать null?

2021-02-10 12:49 UTC, ramilmm commented on src/main/java/com/training/shop/service/Impl/CartInfoImpl.java
> +        if(cartInfo != null){
а если придёт пустой cartInfo? Что произойдёт?

2021-02-10 12:49 UTC, ramilmm commented on src/main/java/com/training/shop/service/Impl/CartLineInfoImpl.java
> +public class CartLineInfoImpl implements CartLineInfo {
Это что? Модель, сервис или репозиторий?

2021-02-10 12:49 UTC, ramilmm commented on src/main/java/com/training/shop/service/Impl/ItemInfoImpl.java
> +public class ItemInfoImpl implements ItemInfo {
Что это? Модель или сервис

2021-02-10 12:49 UTC, ramilmm commented on src/main/java/com/training/shop/service/ItemInfo.java
> +public interface ItemInfo {
Что это

2021-02-15 16:27 UTC, ValeriyEmelyanov commented on src/main/java/com/training/shop/model/Item.java
> +    private Float price;
Для денег везде BigDecimal

2021-02-15 16:28 UTC, ValeriyEmelyanov commented on src/main/java/com/training/shop/model/Cart.java
> +    private Float totalPrice;
Для денег BigDecimal

2021-02-15 16:30 UTC, ValeriyEmelyanov commented on src/main/java/com/training/shop/dto/CartLineDto.java
> +    private BigDecimal amount;
Количество будет дробным? Почему не устраивает int?

2021-02-15 16:30 UTC, ValeriyEmelyanov commented on src/main/java/com/training/shop/model/Cart.java
> +    private Float totalPrice;
Для денег BigDecimal

2021-02-15 16:31 UTC, ValeriyEmelyanov commented on src/main/java/com/training/shop/model/CartLine.java
> +    private BigDecimal amount;
Почему не int?

2021-02-15 16:33 UTC, ValeriyEmelyanov commented on src/main/java/com/training/shop/model/Customer.java
> +    private String patronymic;
Надо сделать как в core firstName, lastName, middleName. На проекте одинаковые понятия должны называться одинаково.

2021-02-15 16:34 UTC, ValeriyEmelyanov commented on src/main/java/com/training/shop/model/Item.java
> +    private Float price;
Для денег BigDecimal

2021-02-15 16:36 UTC, ValeriyEmelyanov commented on src/main/java/com/training/shop/model/Item.java
> +public class Item {
Item это товар? Больше бы подошло product

2021-02-15 16:38 UTC, ValeriyEmelyanov commented on src/main/java/com/training/shop/service/Impl/CartServiceImpl.java
> +    }
Почему без реализации?

2021-02-15 16:41 UTC, ValeriyEmelyanov commented on src/main/java/com/training/shop/model/CartLine.java
> +public class CartLine {
Назвать CartItem было бы более логично

2021-02-21 13:00 UTC, closed without merging